### ISSUE TITLE
Fix build breaks (shinytests + GitHub Actions)

### ISSUE THREAD

**Issue by thiloshon** [bd-R/bdverse-user-guide#2]

**Comment by tom-gu** [comment]
@rahulchauhan049 
- [ ] to check in GitHub forum what to do with phantomJS in Actions
- [ ] to check how RStudio is dealing with this issue

https://github.com/r-lib/actions/tree/master/examples
https://ropenscilabs.github.io/actions_sandbox/
https://www.jimhester.com/talk/2020-rsc-github-actions/

**Comment by tom-gu** [comment]
@thiloshon @rahulchauhan049 
Look what I found:
https://github.com/rstudio/shinycoreci-apps#diagnosing-shinytest-problems-posted-by-github-actions

**Comment by thiloshon** [comment]
Will be handled as part of new devops feature
